# Generated by Django 2.0.5 on 2018-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20180513_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eintrag',
            name='Essen',
        ),
        migrations.AddField(
            model_name='eintrag',
            name='User',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
